### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by superbderrick** [codemaker2015/unity-android-speech-to-text-offline#1]
Hi Mate, Is it working well? 

I tried to build your unity project and then tried to do app but not working any things

**Comment by codemaker2015** [comment]
It is a working version code. Request you to cross check the Unity3D version.

**Comment by superbderrick** [comment]
I used 2020lts version, Can i?;
Thanks for reply

**Comment by codemaker2015** [comment]
Please provide the exact version here. If you are trying it in Unity 2019+ versions then you have to manually select the custom manifest file option from Player Settings -> Publishing Settings. Meanwhile, will cross the compatibility with Unity 2020 LTS.
Thanks for reporting the issue.

**Comment by codemaker2015** [comment]
Hi @superbderrick,
Have upgraded the Unity version to 2020. Now, you can test the same in the Unity 2020.3.31 LTS version. 
I m closing this issue. Thanks for your query.
